### ISSUE TITLE
Something wrong or not update

### ISSUE THREAD

**Issue by eduardotrova** [zdenulo/upload-data-datastore-dataflow#1]
Hello @zdenulo, thanks for your code!

I'm running and I get this error:
raceback (most recent call last):
  File "upload.py", line 9, in <module>
    from google.cloud.proto.datastore.v1 import entity_pb2
ImportError: No module named proto.datastore.v1

It's correct only this modules in requirements.txt ?

**Comment by eduardotrova** [comment]
Hy @zdenulo 

I remove apache-beam from requirements and kept only apache-beam[gcp] and work perfectly.

Thanks for your code. Help a lot.

**Comment by zdenulo** [comment]
great, I'm glad it works. you found a solution before I had a chance to take a look at it.
